export const SILENT_REQUEST_BODY_METADATA = '__SILENT_REQUEST_BODY_METADATA__';
export const SILENT_RESPONSE_BODY_METADATA = '__SILENT_RESPONSE_BODY_METADATA__';
export const SILENT_RESPONSE_LOG_METADATA = '__SILENT_RESPONSE_LOG_METADATA__';
export const SILENT_REQUEST_LOG_METADATA = '__SILENT_REQUEST_LOG_METADATA__';
